// Generated by BUCKLESCRIPT VERSION 4.0.1100, PLEASE EDIT WITH CARE
'use strict';


var Link = /* module */[
  /* name */"IosLink",
  /* hi */"awesomehi"
];

var Camera = /* module */[
  /* name */"MdCamera",
  /* ho */"awesomeho"
];

exports.Link = Link;
exports.Camera = Camera;
/* No side effect */
