// Generated by BUCKLESCRIPT VERSION 4.0.1100, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bsb-native/lib/js/pervasives.js");

var match = 3;

var x = match !== undefined ? Pervasives.failwith("Unwrapped optional") : undefined;

exports.x = x;
/* x Not a pure module */
